"""Write down how every number in the figures and the manuscript is arrived at.

Generated, not written. A hand-written account of a calculation is a second description of that
calculation, and the two drift -- which is the failure this whole pipeline exists to prevent, so
it would be an odd thing to reintroduce in the document that explains it.

Everything here is read out of the code by tools/provenance.py: which check produced a macro,
which check draws a panel, which bundle each check declares, and the source lines themselves.
The lines are the point. They are the calculation, so a reader who doubts a number can read the
arithmetic rather than a paraphrase of it.

    derivation.py                write docs/derivation.md
    derivation.py --check        fail if it is stale (for scripts/derive.sh)
"""
import argparse
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

import provenance

OUT = ROOT / "docs" / "derivation.md"


def render() -> str:
    state = provenance.compute()
    panels = provenance.panels()
    declared = provenance.check_sources()
    macros = state["macros"]
    questions = {row["path"].split("/")[-1].removesuffix(".py"): row["question"]
                 for row in state["checks"]}

    out = [
        "# How every number is arrived at",
        "",
        f"Generated by `tools/derivation.py` on {date.today().isoformat()} from artifact set "
        f"`{state['artifact_hash']}`, commit `{state['commit']}`. Do not edit: it is rewritten "
        f"by `scripts/derive.sh`, and `--check` fails if it has gone stale.",
        "",
        "Nothing in this file is transcribed. The attribution is parsed out of "
        "`tools/paper_numbers.py` and the figure modules, and the code blocks are the source "
        "lines that do the work, so this document cannot describe a calculation the code does "
        "not perform.",
        "",
        "## What everything is computed from",
        "",
        "Seven inputs. The artifact hash above is taken over all of them, so changing any one "
        "changes the hash the manuscript declares.",
        "",
        "| input | path |",
        "| --- | --- |",
    ]
    for label, path in state["bundles"].items():
        out.append(f"| {label} | `{path}` |")

    out += ["", "## The figures, panel by panel", ""]
    for figure, rows in panels.items():
        drawn = state["figures"].get(figure, {})
        out += [f"### `{figure}` &rarr; `{drawn.get('pdf', '')}`", ""]
        out.append("| panel | computed by | which reads |")
        out.append("| --- | --- | --- |")
        for row in rows:
            reads = ", ".join(f"`checks/**/{name}.py`" for name in row["reads"]) or "—"
            inputs = "; ".join(sorted({item for name in row["reads"]
                                       for item in declared.get(name, [])})) or "—"
            out.append(f"| **{row['letter']}** {row['purpose']} | {reads} | {inputs} |")
        out.append("")
        for row in rows:
            span = ", ".join(f"{a}&ndash;{b}" for a, b in row["lines"])
            out += [f"#### Panel {row['letter']} — {row['purpose']}", ""]
            for name in row["reads"]:
                if name in questions:
                    out.append(f"The check behind it asks: *{questions[name]}*")
                    out.append("")
            out += [f"`figures/{figure}.py`, lines {span}:", "", "```python",
                    row["code"], "```", ""]

    quoted = {name: row for name, row in sorted(macros.items()) if row["used"]}
    spare = sorted(name for name, row in macros.items() if not row["used"])

    out += ["## The numbers the manuscript quotes", "",
            f"{len(quoted)} of {len(macros)}. This table is the manuscript's numbers and only "
            f"those: a reader checking a claim wants the value behind it, not a catalogue, and "
            f"the {len(spare)} macros nothing cites were most of what the catalogue held.", "",
            "| macro | value | computed by | what it is |",
            "| --- | --- | --- | --- |"]
    for name, row in quoted.items():
        reads = ", ".join(f"`{c}`" for c in row["checks"]) or "—"
        meaning = row["derivation"].replace("|", "\\|") or "—"
        out.append(f"| `\\{name}` | `{row['value']}` | {reads} | {meaning} |")

    out += ["", "### Computed, checked, and not currently quoted", "",
            f"The other {len(spare)} are recomputed and re-checked on every run like the rest; "
            f"they are simply not cited by the manuscript as it stands, so they are named here "
            f"rather than tabulated. A number moving into the paper needs no work beyond citing "
            f"its macro.", "",
            ", ".join(f"`\\{name}`" for name in spare) + "."]

    out += ["", "## The checks, and what each one reads", ""]
    for row in state["checks"]:
        stem = row["path"].split("/")[-1].removesuffix(".py")
        inputs = "; ".join(declared.get(stem, [])) or "—"
        out += [f"- **`checks/{row['path']}`** — *{row['question']}*  ",
                f"  reads: {inputs}"]

    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(prog="derivation")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/derivation.md is stale")
    args = parser.parse_args()

    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        # the generated-on date changes daily and says nothing about the numbers
        strip = lambda body: "\n".join(line for line in body.splitlines()
                                       if not line.startswith("Generated by"))
        if strip(current) != strip(text):
            print(f"{OUT.relative_to(ROOT)} is stale; run tools/derivation.py")
            raise SystemExit(1)
        print(f"{OUT.relative_to(ROOT)} is current")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    panels = sum(len(rows) for rows in provenance.panels().values())
    print(f"{OUT.relative_to(ROOT)}: {panels} panels, "
          f"{len(provenance.compute()['macros'])} macros")


if __name__ == "__main__":
    main()
