"""Write the reference for every number the manuscripts quote.

artifacts/paper_numbers.tex says what each macro *is*. This says what it *means*: the check that
computed it, the bundle that check read, and why the number is in the argument at all. Values come
from the macro file, prose from tools/macro_catalogue.py, so the two cannot disagree.

The connection is enforced, not trusted. A macro defined with no catalogue entry fails the run,
and so does an entry naming a macro nobody defines. That is the whole point: a number cannot reach
the paper without someone saying where it came from.

    macro_reference.py            write docs/macro_reference.md
    macro_reference.py --check    fail if it is stale or a macro is undocumented
"""
import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from macro_catalogue import CATALOGUE

MACROS = ROOT / "artifacts" / "paper_numbers.tex"
OUT = ROOT / "docs" / "macro_reference.md"
DEFINITION = re.compile(r"^\\newcommand\{\\(\w+)\}\{(.*)\}\s*(?:%\s*(.*))?$")

# The order topics appear in, which is the order the argument is made rather than alphabetical.
ORDER = ["Corpus", "Extraction", "Judge", "Provenance", "Chemistry", "Curated benchmark",
         "Adjudication", "Integrity", "Grader matrix", "Extractor benchmark", "Ablations",
         "Answer-key growth", "Release", "Bookkeeping"]


def defined() -> dict:
    """Every macro in the generated file, with its value and any trailing comment."""
    found = {}
    for line in MACROS.read_text(encoding="utf-8").splitlines():
        match = DEFINITION.match(line.strip())
        if match:
            found[match.group(1)] = (match.group(2), (match.group(3) or "").strip())
    return found


def render(macros: dict) -> tuple[str, list]:
    """The document, and whatever is undocumented."""
    header = [l for l in MACROS.read_text(encoding="utf-8").splitlines() if l.startswith("%")]
    bundles = [l.lstrip("% ").rstrip() for l in header if l.startswith("%   ")]
    stamp = next((l.lstrip("% ") for l in header if "artifact set" in l), "")

    # release_numbers.py already ships a one-line description as a trailing comment on each of
    # its macros, so those are documented at source; only a macro with neither counts as missing.
    missing = sorted(name for name, (_, note) in macros.items()
                     if name not in CATALOGUE and not note)

    by_topic = defaultdict(list)
    for name, (value, note) in macros.items():
        if name in CATALOGUE:
            topic, script, reads, meaning = CATALOGUE[name]
        else:
            # release_numbers.py already ships its own one-line description as a trailing comment
            topic, script, reads, meaning = ("Release", "release/release_numbers.py",
                                             "release/pet_homogeneous_release.csv",
                                             note or "**undocumented — add to macro_catalogue.py**")
        by_topic[topic].append((name, value, script, reads, meaning))

    out = [
        "# What every number in the manuscripts means", "",
        "One row per LaTeX macro: what it is, which check computed it, and which bundle that",
        "check read. Generated by `tools/macro_reference.py` from `artifacts/paper_numbers.tex`",
        "and `tools/macro_catalogue.py` — do not edit by hand.", "",
        f"`{stamp}`", "",
        "## Where the numbers come from", "",
        "Every value below is computed by a check in `checks/`, never typed. The checks read these",
        "bundles:", "",
    ]
    out += [f"- `{b}`" for b in bundles]
    out += [
        "", "Two generators write the macro file: `tools/paper_numbers.py` for the study, and",
        "`checks/release/release_numbers.py` for the released dataset. Regenerate both with",
        "`scripts/paper.sh`.", "",
        "> **The Database\\* and Release\\* families are different populations.** `Database*`",
        "> describes the mass extraction run (every record the model produced). `Release*`",
        "> describes the filtered homogeneous dataset that ships. Never mix them in one sentence.",
        "",
    ]
    for topic in ORDER + sorted(set(by_topic) - set(ORDER)):
        rows = sorted(by_topic.get(topic, []))
        if not rows:
            continue
        out += [f"## {topic}", "",
                "| Macro | Value | Computed by | Reads | What it is |",
                "|---|---|---|---|---|"]
        for name, value, script, reads, meaning in rows:
            clean = value.replace("{,}", ",").replace("\\times", "×").replace("^{-7}", "⁻⁷")
            out.append(f"| `\\{name}` | {clean} | `{script}` | `{reads}` | {meaning} |")
        out.append("")
    return "\n".join(out) + "\n", missing


def main() -> None:
    parser = argparse.ArgumentParser(prog="macro_reference")
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    args = parser.parse_args()

    macros = defined()
    document, missing = render(macros)
    stale = sorted(set(CATALOGUE) - set(macros))

    print(f"{len(macros)} macros, {len(CATALOGUE)} catalogue entries")
    if missing:
        print(f"\n{len(missing)} macro(s) defined with no catalogue entry:")
        for name in missing:
            print(f"  \\{name}")
        print("  add them to tools/macro_catalogue.py")
    if stale:
        print(f"\n{len(stale)} catalogue entr(ies) for a macro nobody defines:")
        for name in stale:
            print(f"  \\{name}")

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != document:
            print(f"\n{OUT.relative_to(ROOT)} is stale; run tools/macro_reference.py")
            sys.exit(1)
        if missing:
            sys.exit(1)
        print("\nup to date")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(document, encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
