"""Stand-in adjudication decisions, so the plots and tables can be built before the chemists finish.

THIS INVENTS DATA. Every file it writes is named SIMULATED_*, carries "simulated": true at the
top level, and records the rates it sampled from. Nothing here is evidence about anything, and no
number computed from it belongs in the paper. It exists so the analysis downstream of the
adjudication -- checks/human/adjudicated.py, the tables, the figure panels -- can be written and
debugged now and pointed at the real decisions the moment they arrive, instead of being written
in a rush against data nobody has looked at yet.

The real worklist is used, not a made-up one: the same 115 records, the same three strata, the
same weights, and the 34 disagreements the rescue review already ruled on keep their real
answers. Only the 81 undecided records are invented.

The rates are not guesses either; they are the values the surrounding analysis already assumes,
so a simulated run lands in the region the real one is expected to:

  graders disagree    P(correct) = 0.59   the rescue review's own rate on this stratum
                                          (16 real of the 27 it decided either way)
  both flagged it     P(correct) = 0.25   both graders called it wrong, and checks/human/
                                          precision.py works at a judge precision near 0.75
  both accepted it    P(correct) = 0.95   precision.py's central recall scenario is a 5%
                                          chemist rejection rate among agreed records

    simulate_decisions.py                          the 50-agreement worklist
    simulate_decisions.py --agreements 20
    simulate_decisions.py --reject-agreed 0.10     the pessimistic recall scenario
"""
import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "checks"))

from core.paths import ARTIFACTS
from human import worklist as worklist_check

CARRY = {"real": "correct", "notreal": "incorrect"}
SEED = 20260824

WARNING = ("SIMULATED DATA -- NOT HUMAN DECISIONS. Generated by tools/simulate_decisions.py so "
           "the analysis could be built before the chemists finished. No number derived from "
           "this file may appear in the paper.")


def main() -> None:
    parser = argparse.ArgumentParser(prog="simulate_decisions")
    parser.add_argument("--agreements", type=int, default=50,
                        help="which worklist size to stand in for")
    parser.add_argument("--disagree-correct", type=float, default=0.59)
    parser.add_argument("--both-flagged-correct", type=float, default=0.25)
    parser.add_argument("--reject-agreed", type=float, default=0.05,
                        help="share of both-accepted records a chemist rejects")
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    work = pd.DataFrame(worklist_check.compute())
    rates = {"graders disagree": args.disagree_correct,
             "both flagged it": args.both_flagged_correct,
             "both accepted it": 1.0 - args.reject_agreed}

    rng = np.random.default_rng(args.seed)
    decisions, carried, invented = [], 0, 0
    for _, row in work.iterrows():
        prefilled = CARRY.get(str(row["prefilled"]))
        if prefilled:                       # a real answer from the rescue review; keep it
            human, source = prefilled, "carried over from the rescue review (real)"
            carried += 1
        else:
            probability = rates[row["stratum"]]
            human = "correct" if rng.random() < probability else "incorrect"
            source = f"SIMULATED at P(correct)={probability:.2f}"
            invented += 1
        decisions.append({
            "doi": row["doi"], "extracted_index": int(row["index"]),
            "human": human, "stratum": row["stratum"], "weight": float(row["weight"]),
            "note": source, "carried_over": bool(prefilled),
            "simulated": not bool(prefilled),
        })

    payload = {
        "simulated": True,
        "WARNING": WARNING,
        "generated": datetime.now(timezone.utc).isoformat(),
        "generator": "tools/simulate_decisions.py",
        "seed": args.seed,
        "rates": rates,
        "sample": {"records": len(decisions), "carried_over": carried, "simulated": invented},
        "decisions": decisions,
    }

    out = Path(args.out) if args.out else (
        ARTIFACTS / "gold" / "decisions" / f"SIMULATED_adjudication_{args.agreements}agree.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    frame = pd.DataFrame(decisions)
    print(WARNING)
    print()
    print(frame.groupby("stratum").agg(records=("human", "size"),
                                       correct=("human", lambda s: int((s == "correct").sum())),
                                       carried=("carried_over", "sum")))
    print(f"\ncarried over from real decisions {carried}")
    print(f"invented                         {invented}")
    print(f"\nwrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
