"""Does the manuscript body quote anything the checks did not compute?

Every number in the papers is meant to come from artifacts/paper_numbers.tex, written from the
checks, and every figure caption from the figure module that drew it. Both are regenerated by
scripts/paper.sh and both already refuse to go stale. The hole between them is the body text: a
literal typed beside a macro looks identical on the page and moves only when someone remembers.
The abstract cited \\AdjFavourJudge of \\AdjPairs while the conclusion two pages later said "43 of
51" in plain text -- both right on the day, and only one of them would survive the next run.

So for every value a macro defines, this looks for the same value typed out as a bare literal in
the body. A hit is a number that will not move when the checks move.

This scan earns its place: on its first honest run -- the DEFINITION regex had been silently
missing every macro with a trailing comment, so 36 of them, including both numbers in the
abstract, were never scanned -- it found \\textbf{0.935} typed into the agreement table two cells
from \\MatrixEvaluableHigh{} reading the same grid, with the bold on the wrong maximum.

What is deliberately not scanned: the preamble, where 15pt and 0.5\\textfloatsep are typography
rather than claims; \\caption blocks, which sync_captions.py rewrites from the figures; and any
number carrying a unit. What is scanned but excused is listed in REVIEWED below -- coincidences,
where a macro's value happens to equal an unrelated constant, each with the reason. A coincidence
excused by value alone would hide a real one, so each entry names the macro and the context.
"""
import re

import pandas as pd

from _setup import ARTIFACTS, ROOT, show, sources

MACROS = ARTIFACTS / "paper_numbers.tex"
PAPERS = ("paper_rsc.tex",)   # paper.tex and paper_rsc_si.tex were deleted, not renamed
# The released-dataset macros carry a trailing "  % derivation" comment, which the original
# "\}\s*$" refused to match -- so all 36 of them counted as undefined, and \ReleaseRecords and
# \ReleasePapers, the two numbers in the abstract, sat outside every guard in this file.
DEFINITION = re.compile(r"\\newcommand\{\\(\w+)\}\{(.+?)\}(?:\s*%.*)?$", re.M)
# Whether a macro exists at all is a different question from what its value is: \MatrixTableRows
# and \FieldTableRows hold whole table bodies over several lines, which DEFINITION cannot match
# and should not try to.
DEFINED = re.compile(r"\\newcommand\{\\(\w+)\}")
USE = re.compile(r"\\([A-Z][A-Za-z]*)")

# LaTeX's own capitalised control sequences, which appear in the body and are not ours. Short
# list on purpose: anything else matching \Capitalised is a paper macro, and if it is not
# defined the manuscript is quoting a number that no longer exists.
LATEX = {"Large", "LARGE", "Huge", "HUGE", "Roman", "Alph", "AA", "LaTeX", "TeX", "S",
         "IfFileExists"}
CAPTION = re.compile(r"\\caption\{")
UNIT = re.compile(r"(pt|in|em|ex|cm|mm|\\textfloatsep|\\textwidth|\\columnwidth|\\linewidth)")
# \@setfontsize{12pt}{14} is typography, and the RSC template's block of them sits *after*
# \begin{document}, so body() cannot strip it as preamble. UNIT only looks forward, and the
# second argument of a setfontsize call is followed by a brace rather than a unit.
TYPOGRAPHY = re.compile(r"@setfontsize|\\the\\|setlength")

# Macro values that also appear as unrelated constants. Each is a real coincidence, not a number
# anyone should have written as a macro.
REVIEWED = {
    ("ShotsSmallestPairwise", "0.02"): "0.02 as a detectable-difference size in the power tables",
    ("ShotsComparisons", "10"): "unrelated counts of ten",
    ("AdjCarriedOver", "20"): "the 20 rescue-review prefills, and unrelated counts of 20",
    ("AdjDecidedFresh", "92"): "unrelated count of 92 enzymatic papers",
    ("MatrixGapHigh", "12"): "12pt font sizes and the both-flagged stratum",
    ("SourceCitingSd", "0.021"): "the pooled standard deviation in the power paragraph",
    ("SourceNotSd", "0.043"): "the pooled standard deviation in the power paragraph",
    ("AnnotatorsShared", "27"): "27% power to detect a 0.03 difference, in the sizing paragraph",
    ("ConstraintOverHundredCaught", "100"): "100k tokens, the context ceiling being tested",
    ("BenchmarkInCorpus", "12"): "12pt font sizes in the RSC preamble",
    ("AdjBothFlagged", "12"): "12pt font sizes in the RSC preamble",
    ("ThresholdAcceptBest", "0.5"): "McNemar tests against p = 0.5",
    ("ThresholdToleranceBest", "0.5"): "McNemar tests against p = 0.5",
    ("AdjMetricKappa", "0.21"): "the bootstrap interval [-0.21, -0.02] on the growth contrast",
    ("AdjJudgeKappa", "0.30"): "the worked penalty example, and the accept threshold itself",
    ("AdjPowerAtSixty", "0.30"): "the worked penalty example, and the accept threshold itself",
    ("AdjMetricFlagged", "60"): "the catalyst gate is 60% similarity",
    ("ConversionCoverage", "48"): "the earlier round adjudicated 48 records",
    ("AdjFavourJudge", "43"): "the growth table adds 43 records to the key",
    ("AdjAcceptedDrawn", "50"): "the worked examples add about 50k tokens to a prompt",
    ("AdjJudgeFlagged", "15"): "a power percentage in the shots discussion",
    ("ShotsAnovaP", "0.03"): "an effect size in the shots power discussion",
    ("YieldOverHundred", "19"): "the draft date, and the superseded round's tables in paper.tex",
    ("GrowthVouchedAdded", "43"): "also the pairs favouring the judge",
    ("GrowthVouchedExperiments", "338"): "also the count of Wiley papers we cannot read",
    ("WithinPaperPositive", "85"): "the judge's 85% agreement with human assessment, in the abstract",
    ("CuratedOverlapPapers", "11"): "the 11 papers excluded as reviews without protocols",
    ("WithinRoutePairs", "11"): "also the 11 papers excluded as reviews without protocols",
    ("GaoMissed", "12"): "the schema's 12 fields per record",
    ("WithinRouteTotal", "12"): "the schema's 12 fields per record",
}


def strip_captions(text: str) -> str:
    """Remove each \\caption{...} whole. A caption runs to its matching brace and contains plenty
    of its own, so counting depth is the only way to find where it ends."""
    out, position = [], 0
    for match in CAPTION.finditer(text):
        if match.start() < position:
            continue
        out.append(text[position:match.start()])
        depth, index = 1, match.end()
        while index < len(text) and depth:
            if text[index] == "\\":
                index += 2
                continue
            depth += (text[index] == "{") - (text[index] == "}")
            index += 1
        position = index
    out.append(text[position:])
    return " ".join(out)


def body(text: str) -> str:
    """The manuscript without its preamble, its comments, or its generated captions."""
    start = text.find("\\begin{document}")
    text = text[start:] if start >= 0 else text
    text = "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("%"))
    return strip_captions(text)


def informative(value: str) -> bool:
    """Whether a macro's value is specific enough that seeing it typed out means something."""
    bare = value.replace(",", "").replace("\\%", "").strip()
    if not re.fullmatch(r"\d+(\.\d+)?", bare):
        return False                                    # p-values, ranges, anything with markup
    return float(bare) >= 10 or "." in bare


def hits(text: str, value: str) -> list[str]:
    """Each place `value` appears as a bare number rather than through a macro."""
    pattern = re.compile(rf"(?<![\d.\\]){re.escape(value)}(?![\d.])")
    found = []
    for match in pattern.finditer(text):
        tail = text[match.end():match.end() + 14]
        if UNIT.match(tail.lstrip()):
            continue                                    # 15pt, 0.5\textfloatsep: typography
        context = text[max(0, match.start() - 60):match.end() + 45]
        if TYPOGRAPHY.search(context):
            continue                                    # a font-size declaration, not a claim
        found.append(" ".join(context.split()))
    return found


def undefined(text: str, defined) -> list[str]:
    """Macros the body uses that the macro file does not define.

    This is the direction that actually breaks a manuscript, and it was the direction nobody
    checked. The body cited \\AdjWithinRho and \\AdjWithinPositive for two revisions after the
    check that computes them renamed both to WithinPaper*; LaTeX prints "Undefined control
    sequence" into a log nobody reads and carries on.
    """
    return sorted({name for name in USE.findall(text)
                   if name not in defined and name not in LATEX})


def compute() -> dict:
    sources = [MACROS, ARTIFACTS / "paper_table_fields.tex", ARTIFACTS / "paper_table_matrix.tex"]
    text = "\n".join(p.read_text(encoding="utf-8") for p in sources if p.exists())
    defined = dict(DEFINITION.findall(text))
    exists = set(DEFINED.findall(text))
    broken = {}
    findings, excused = [], []
    for paper in PAPERS:
        path = ROOT / paper
        if not path.exists():
            continue
        text = body(path.read_text(encoding="utf-8"))
        missing = undefined(text, exists)
        if missing:
            broken[paper] = missing
        for name, value in sorted(defined.items()):
            if not informative(value):
                continue
            for context in hits(text, value):
                row = {"paper": paper, "macro": f"\\{name}", "value": value, "context": context}
                (excused if (name, value) in REVIEWED else findings).append(row)
    return {"defined": defined, "exists": exists, "findings": findings, "excused": excused,
            "broken": broken}


def main() -> None:
    sources(macros=MACROS)
    result = compute()
    print(f"\n{len(result['defined'])} macros defined, body text of {len(PAPERS)} manuscripts "
          f"scanned")
    print(f"  captions are not scanned: sync_captions.py rewrites them from the figures")
    print(f"  {len(result['excused'])} known coincidence(s) excused by name in REVIEWED")

    if result["broken"]:
        for paper, names in result["broken"].items():
            print(f"\n  {paper} uses macros nothing defines:")
            for name in names:
                print(f"    \\{name}")
        print("\n  each of these prints \"Undefined control sequence\" and builds anyway.")
        raise SystemExit(1)
    print("  every macro the body uses is defined")

    findings = result["findings"]
    if not findings:
        print("\nno literal in either body duplicates a computed value")
        return

    frame = pd.DataFrame(findings)
    show("values typed out that a macro already defines",
         frame.groupby(["paper", "macro", "value"]).size().rename("times"), fmt="{:.0f}")
    print()
    for row in findings:
        print(f"  {row['paper']}  {row['macro']}")
        print(f"    …{row['context']}…")
    print("\n  each of these is a number that will not move when the checks move.")
    print("  replace the literal with the macro, or add it to REVIEWED with its reason.")
    raise SystemExit(1)


if __name__ == "__main__":
    main()
